import React from 'react';

const HomePage = () => {
  return (
    <React.Fragment>
      HOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHITHOME SHIT
    </React.Fragment>
  )
}

export default HomePage;